microservices/frontend/app/forms/__init__.py
from flask import Blueprint

bp = Blueprint('forms', __name__)

microservices/frontend/app/forms/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FileField
from wtforms.validators import DataRequired


class SubmitStockForm(FlaskForm):
    stock = StringField('New Stock', validators=[DataRequired()])
    logo = FileField('Upload Logo', validators=[DataRequired()])
    submit = SubmitField('Submit')

microservices/frontend/app/__init__.py
import os, logging
from logging.handlers import RotatingFileHandler
from flask import Flask
from flask_bootstrap import Bootstrap
from config import Config

bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    bootstrap.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    if not app.debug and not app.testing:

        if app.config['LOG_TO_STDOUT']:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.INFO)
            app.logger.addHandler(stream_handler)
        else:
            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/stock_of_the_day.log', maxBytes=10240,
                                               backupCount=10)
            file_handler.setFormatter(logging.Formatter(
                '%(asctime)s %(levelname)s: %(message)s '
                '[in %(pathname)s:%(lineno)d]'))
            file_handler.setLevel(logging.INFO)
            app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Stock of the Day startup')

    return app

microservices/frontend/app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

microservices/frontend/app/main/routes.py
import json
import logging

import requests, os
from flask import render_template, current_app, flash, redirect, url_for
from tenacity import before_log, retry, stop_after_attempt
from app.main import bp
from app.forms.forms import SubmitStockForm

logger = logging.getLogger('routes')


@bp.route('/')
@bp.route('/index', methods=['GET', 'POST'])
def index():
    response = requests.get(current_app.config['STOCK_SYMBOL_SERVICE_URL'])
    data = response.json()
    stock = {'name': data['stock']['name'],
             'logo_url': data['stock']['logo_url']}
    return render_template('index.html', title='Home', stock=stock)


@bp.route('/addstock', methods=['GET', 'POST'])
@retry(stop=stop_after_attempt(5),
       before=before_log(logger, logging.DEBUG))
def add_stock():
    form = SubmitStockForm()
    if form.validate_on_submit():
        save_logo(logo_file=form.logo.data, stock_name=form.stock.data)
        save_stock(form.stock)
        flash('Thank you for submitting a new stock symbol!')
        return redirect(url_for('main.index'))
    return render_template('addstock.html', title='Add New Stock Symbol', form=form)


def save_stock(stock_name):
    data = {'name': stock_name.data}

    requests.post(current_app.config['STOCK_SYMBOL_SERVICE_URL'], json=data)
    return 'OK'


def save_logo(logo_file, stock_name):
    filename = stock_name + '.jpeg'
    logo_file.save('./' + filename)
    file_path = './' + filename

    data = open(file_path, 'rb').read()
    stock_name = {'name': stock_name}

    stock = {
        'name': (None, json.dumps(stock_name), 'application/json'),
        'image': data
    }
    requests.post(current_app.config['LOGO_RESIZER_SERVICE_URL'], files=stock)
    os.remove(file_path)


@bp.route('/api/ping', methods=["GET"])
def ping():
    return 'OK'

microservices/frontend/app/templates/addstock.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1 style="margin-left: 130px">Add New Stock Symbol</h1>
    <div class="row" style="margin-left: 120px">
        <div class="col-md-2">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

microservices/frontend/app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Stock-of-the-Day{% else %}Welcome to Stock-of-the-Day{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Stock-of-the-Day</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('main.add_stock') }}">Add Stock</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    {% block app_content %}{% endblock %}
{% endblock %}

microservices/frontend/app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <p id="stockSymbol" class="container">
        <img src="{{ stock.logo_url }}">
        {{ stock.name }}
    </p>
{% endblock %}